name: timorya
services:
  timorya-api:
    container_name: timorya-api
    build:
      context: ./backend
      dockerfile: Dockerfile
      args:
        - BUILD=Release
    image: timorya-api
    env_file:
      - .env.production
    ports:
      - "6000:80"
    volumes:
      - ./backend/https-cert.pfx:/app/https/https-cert.pfx:ro
    restart: always

  timorya-frontend:
    container_name: timorya-frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: timorya-frontend
    env_file:
      - .env.development
    ports:
      - "4000:4000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - timorya-api
    restart: always

volumes:
  postgres_data:
    driver: local
