name: timorya
services:
  timorya-api:
    container_name: timorya-api
    build:
      context: ./backend
      dockerfile: Dockerfile
      args:
        - BUILD=Release
    image: timorya-api
    env_file:
      - .env.production
    ports:
      - "6000:80"
    restart: always
    networks:
      - rahat-kuca_default
      - default


  timorya-app:
    container_name: timorya-app
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL}
        NEXT_PUBLIC_ENVIRONMENT: ${NEXT_PUBLIC_ENVIRONMENT}
    image: timorya-app
    environment:
      - PORT=4000
    env_file:
      - .env.production
    ports:
      - "4000:4000"
    depends_on:
      - timorya-api
    restart: always

networks:
  rahat-kuca_default:
    external: true